### ISSUE TITLE
Spark Histogram are rendered as symbols in html/md

### ISSUE THREAD

**Issue by OmaymaS** [ropenscilabs/skimr#136] opened 2017-09-11 22:02 UTC
Although the following code displays the histograms properly when I run the chunk in rmd, it turns into symbols in the rendered html or the md.

```
library(tidyverse)
library(skimr)

Sys.setlocale("LC_CTYPE", "Chinese")

skim(storms) %>% filter(stat=="hist")
```

```
# A tibble: 10 x 5
           var    type  stat      level value
         <chr>   <chr> <chr>      <chr> <dbl>
 1        year numeric  hist ¨z¨z¨z¨}¨~¨}¨~¨~¨~¨}     0
 2       month numeric  hist ¨x¨x¨x¨x¨x¨y¨|¨~¨z¨x     0
 3         day integer  hist ¨~¨}¨}¨}¨}¨}¨}¨}¨}¨}     0
 4        hour numeric  hist ¨~¨x¨~¨x¨x¨~¨x¨~¨x¨x     0
 5         lat numeric  hist ¨y¨~¨~¨}¨~¨~¨|¨y¨x¨x     0
 6        long numeric  hist ¨x¨|¨~¨~¨~¨}¨}¨z¨x¨x     0
 7        wind integer  hist ¨y¨~¨|¨z¨y¨y¨x¨x¨x¨x     0
 8    pressure integer  hist ¨x¨x¨x¨x¨x¨x¨y¨z¨~¨y     0
 9 ts_diameter numeric  hist ¨~¨~¨|¨y¨x¨x¨x¨x¨x¨x     0
10 hu_diameter numeric  hist ¨~¨x¨x¨x¨x¨x¨x¨x¨x¨x     0
```

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252   LC_CTYPE=Chinese (Simplified)_China.936
[3] LC_MONETARY=English_United States.1252  LC_NUMERIC=C                           
[5] LC_TIME=English_United States.1252     

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2    skimr_0.9000    dplyr_0.7.3     purrr_0.2.3     readr_1.1.1     tidyr_0.7.1     tibble_1.3.4   
[8] ggplot2_2.2.1   tidyverse_1.1.1

loaded via a namespace (and not attached):
 [1] colformat_0.0.0.9000 tidyselect_0.2.0     reshape2_1.4.2       haven_1.0.0          lattice_0.20-35     
 [6] colorspace_1.3-2     htmltools_0.3.6      yaml_2.1.14          rlang_0.1.2          foreign_0.8-67      
[11] glue_1.1.1           modelr_0.1.0         readxl_1.0.0         bindr_0.1            plyr_1.8.4          
[16] stringr_1.2.0        munsell_0.4.3        blogdown_0.0.42      gtable_0.2.0         cellranger_1.1.0    
[21] rvest_0.3.2          psych_1.7.5          evaluate_0.10        knitr_1.16           forcats_0.2.0       
[26] gapminder_0.2.0      parallel_3.4.0       broom_0.4.2          Rcpp_0.12.12         scales_0.4.1        
[31] backports_1.1.0      jsonlite_1.5         mnormt_1.5-5         hms_0.3              digest_0.6.12       
[36] stringi_1.1.5        bookdown_0.4         grid_3.4.0           rprojroot_1.2        tools_3.4.0         
[41] magrittr_1.5         lazyeval_0.2.0       crayon_1.3.2.9000    pkgconfig_2.0.1      rsconnect_0.8       
[46] xml2_1.1.1           lubridate_1.6.0      assertthat_0.2.0     rmarkdown_1.6        httr_1.2.1          
[51] rstudioapi_0.6       R6_2.2.2             nlme_3.1-131         compiler_3.4.0   
```

**Comment by elinw** [comment] 2017-09-12 18:27
Are you on Windows and did you read the instructions for Windows in the readme file?

**Comment by OmaymaS** [comment] 2017-09-12 18:39
Yes I am on windows, I read the instructions, that's why I used `Sys.setlocale("LC_CTYPE", "Chinese")`

The point is, I see the spark histogram shown properly on the when I run the chunk in .Rmd file or when I View() the dataframe. But when I knit the file, the html/md show symbols.

**Comment by elinw** [comment] 2017-09-12 19:33
Is this when knitting to PDF? I'll say that right now for me that is not working for hist at all (html is fine). In fact it stops processing. However adding latex_engine: xelatex to the YAML at least gets it to run. http://rmarkdown.rstudio.com/pdf_document_format.html#advanced_customization.

When did you install? Was it since this morning? There were changes made to the dependency that manages those, which I guess could have an impact.

**Comment by OmaymaS** [comment] 2017-09-12 19:40
It happens with both, knitting to html as well pdf. I am more interested in the html now.
And I have installed it this week or 2 weeks ago, definitely before this morning.

**Comment by elinw** [comment] 2017-09-12 19:54
Before I changed the latex engine pdf was dying.  Now it knits but blank for both line_graph and hist.  Html is working.  I'm on a mac.    I'll have to try to look into this but I suspect it might have to do with the character sets. I'm also going to see if pillar (formerly colformat) has this same issue outside of skimr.

**Comment by elinw** [comment] 2017-09-13 18:49
I think the issue is that you need a font that supports the building block drawing characters an for braille.   It seems like DejaVu would be the free one that is most commonly used.  However, while I have figured out how to change the font of the text I haven't figured out how to get the <pre> regions to accept a new font.  Also I haven't figured out how to access DejaVu.

**Comment by elinw** [comment] 2017-09-13 21:37
Okay here is an update.  The important thing, as described in the pillar readme file, is that you have a font installed that has block building characters.  There are a number of these one of which is Dejavu Sans.   

For my mac I used homebrew.
```
brew tap caskroom/fonts
brew cask install font-dejavu-sans
```
At the top of my rmd file I changed my YAML to reference the font.

```
---
title: "Untitled"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
font-family: "DejaVu Sans"
mainfont: "DejaVu Sans"
---
```
Remember that spaces matter in YAML so be careful. 
HTML was working for me already and this continued fine. However now in PDF I still can't get the graphs embedded in the code chunk output that is formatted with `<pre>`.     However, unlike previously I can get the spark graphs inline as below.

![screen shot 2017-09-13 at 5 32 15 pm](https://user-images.githubusercontent.com/754813/30401857-a9c748de-98a9-11e7-9082-e40de49a3074.png)

So for Windows you will need to figure out how to install a font that supports block building and also braille.  

If you could try that and then report back that would be awesome. There are a number of places that explain how depending on your version etc.

We still need to figure out the issue for pre formatted sections in PDFs.

**Comment by elinw** [comment] 2017-09-14 15:01
Okay, one more update ... the real answer for me is using `results=asis` in the code chunk options and then using kable (or I assume something else) to format the table. 

![screen shot 2017-09-14 at 10 51 20 am](https://user-images.githubusercontent.com/754813/30437188-fdbc7a76-993b-11e7-874e-5c8e3fb8a69c.png)

**Comment by OmaymaS** [comment] 2017-09-15 23:49
Thanks!
I could finally knit to html by using kable. I added examples [here](http://www.onceupondata.com/2017/09/15/spark-histograms/). However, if I don't use kable, the histograms so not  appear properly. Will check it out,  check the PDF and get back to you.

**Comment by elinw** [comment] 2017-11-18 00:43
@OmaymaS did you ever have an update on this? Now we have pull requests to support kable and pander.  Can I close this issue and we can open a new one for a branch including that support? I think we also need to document some things about fonts. i think we may need to suggest extrafonts.

**Comment by ak-koli** [comment] 2017-12-03 04:22
@elinw 
I'm sorry for late reply, PhD thesis writing torturing me. You are absolutely write about the types of font use and skimr summary output. For me, latex pdf bring histogram figure only with the fonts: 
`font-family: "DejaVu Sans"`
`mainfont: "DejaVu Sans"`, suggested by you.  But the same file gives empty hist column if I use font:
`mainfont: EB Garamond`

I got this nice output with your present and earlier suggestions. Can you suggest something to remove the last 'value' column, it is full of zeros - seems not so important.

![screenshot from 2017-12-03 09-49-58](https://user-images.githubusercontent.com/28312545/33522317-b0b0d21e-d80f-11e7-88a0-e675fd0c21e3.png)

**Comment by elinw** [comment] 2017-12-03 04:26
Yes since we have added the formatted values column the spark graphs have only the formats and are all set to 0. 
So in this case value is really not useful to display and could be dropped.  That can be done by using dplyr::select() and dropping the value.

**Comment by ak-koli** [comment] 2017-12-03 04:29
Thank you @elinw  :)

**Comment by ak-koli** [comment] 2017-12-03 05:24
@elinw , I've a suggestion, is it not possible to provide the no. of observations and variables information too at footnote of the descriptive table? Because when we produce table using kable and skim, the info about the number of variables and observations is lost, the way it comes when we use only `skim()`

**Comment by elinw** [comment] 2017-12-05 18:04
Oh that’s an interesting idea.  I’m still not totally sure that we shouldn’t make some more flexible way of handling that data in general (so people could suppress it in regular printing).  A footnote could make sense but so could a summary block (see the pull request for a summary).  If you want to try to play around with that concept feel free to send a pull request.

**Comment by ak-koli** [comment] 2017-12-05 19:38
@elinw , but I know exactly zero about `pull request` and how to contribute in it. :-(

**Comment by elinw** [comment] 2017-12-06 01:54
I looked at the code and in pander() and kable() there is the caption parameter, so we can definitely put the separate table text in there at least for now.  And adding the header text the way we do for print is also easy so we can do it for now (but long run I'd like something better). Pull request coming soon.

**Comment by ak-koli** [comment] 2017-12-06 04:23
Thank you @elinw  :-)
Once, I'm done with my thesis. I'll make myself more friendly with the technicalities of GitHub, R packages and latex.

**Comment by elinw** [comment] 2017-12-19 23:38
This is still an issue that we haven't solved.  It's not clear if it is possible, but I'd rather at least have it showing as an issue so people know we are aware of it.

**Comment by koliii** [comment] 2017-12-20 03:09
Sure, you are right.

**Comment by elinw** [comment] 2018-01-07 02:32
https://github.com/ropenscilabs/skimr/pull/209   Please test the develop branch if you can, it should resolve the Windows-histogram issue.

**Closed** 2018-01-08 23:31 UTC
Labels: knitting
