### ISSUE TITLE
Strange behavior of numeric variables when using `skim_to_wide()`

### ISSUE THREAD

**Issue by Z3tt** [ropenscilabs/skimr#265] opened 2018-01-26 16:22 UTC
Hi together,

Thank you very much for those nice summary tables, very helpful. 

I figured out some strange behavior when using `skim_to_wide()`. Without showing the variable `prop` the summary looks as expected but when adding `prop` to the summary, some output of numeric varibales is quoted.

Below is the code for reproducibility and I added also a screenshot of the summary tables as well as the session info.

```
library(skimr); library(tidyverse); library(babynames)

## no quotation marks for values of numeric variables
babynames %>% select(n, year) %>% skim_to_wide()

## suddenly, quotation marks appear for values of numeric variables
babynames %>% select(n, year, prop) %>% skim_to_wide()
```

I actually don't know if it is a bug (or a feature) nor how to approach that issue by myself. Would be nice to get some feedback.

Best, Cédric

![skim_to_wide](https://user-images.githubusercontent.com/7523556/35449331-0c559320-02bd-11e8-9ebf-2db39600060a.PNG)

**Comment by elinw** [comment] 2018-01-26 17:53
All of the variables in skim_to_wide are quoted,  because basically it is giving you the printed version you get on the screen or in you knitted file. That's how there can be histograms and different numbers of decimals--they are all string data.   So I'm guessing that the prop data  has a lot of digits and that you might want to apply custom formatting to it (see the vignette).  
I'm actually curious about the scientific notation also.  I wonder if there is some kind of double quoting happening with these variables that is making the inner quote show up.  Can you take a look View() at the skim object and see what is in the formatted values column for those variables?

**Comment by elinw** [comment] 2018-01-26 17:59
I can confirm this, it's interesting that it only happens with numerics and not integers.

**Comment by elinw** [comment] 2018-01-26 18:13
Okay if you do this:`
babynames %>%  skim(select(n, prop, year))`

it works the way you would expect.  so there is something with using the select() as part of a pipe that is impacting things.

**Comment by Z3tt** [comment] 2018-01-26 18:43
The View() shows no quotations neither does the base commands summary() and str() or dplyr's glimpse(). 

The prop data has a lot of digits, that is right. I also realized that conversion to integers solves indeed the problem (but is no solution here). 

I am using a different machine now. The double quote issue is not reproducible here and putting select inside the skim function displays an error in my case: `Error in UseMethod("select_") : no applicable method for 'select_' applied to an object of class "function"`.

-> tibble package versions were different (1.3.x on this machine now), updating tibble to 1.4.2 brings back the double quotes when running select() first. Unfortunately, the errorwhen using skim(select(...) is still around and using `babynames %>% skim_to_wide(select(n, year, prop))` prints still double-quoted values.

**Comment by elinw** [comment] 2018-01-26 21:02
select() not select_()
I thought maybe it was the long digits or the scientific notation but got weird results even with iris.

Interestingly this worked for me 
`iris %>% dplyr::select(Sepal.Length, Sepal.Width) %>%  skim_to_wide() %>% kable()`

I think it must relate to the print function because with iris on my screen and not using kable() I got quotes for some numbers but not others.   Still digging into it.

**Comment by Z3tt** [comment] 2018-01-26 21:40
I did use select() without an underscore (see screenshot) but always wondering about that strange error message. 

![select](https://user-images.githubusercontent.com/7523556/35461602-c0a93c02-02e8-11e8-9ba2-633b05e7f510.JPG)

When I use the iris data, it gives me an error that the variable cannot be found (but it works using skim_to_wide()):

![iris](https://user-images.githubusercontent.com/7523556/35461726-51f044b2-02e9-11e8-8371-9c1c71fdb797.JPG)

Combining it with kable() does result in double-quote-free tables for my examples, too.

Thanks for digging into it.

**Comment by elinw** [comment] 2018-01-27 21:39
Lower case w in your variable name is why you are getting variable not found.

Babynames has row names so you do need to strip them or you get warnings (I already opened an issue for that).

I'm not sure why it's showing the quotes sometimes, each time I see  a pattern I find something that doesn't fit.   The thing is that I think that if you print you should do regular skim which has its own complex print function. `skim_to_wide()` and `skim_to_list()` are just producing data frames or lists of data frames because people wanted to have those for further processing.  So this print is just the R base print.data.frame function which has very deep handling of formats for character variables.  So I suspect the issue is related to that.

**Comment by elinw** [comment] 2018-01-28 19:21
I think that the pattern is that if there are an enclosed spaces it displays the quotation marks and if not it does not display them. There is a certain logic to that.  The formatted values have to all be the same width in the same column to allow the decimals to align even though there are different numbers of digits (and for integers no decimal is present).

**Comment by elinw** [comment] 2018-01-29 02:34
Another option is go get the numeric data rather than the formatted data. This loses the histograms and replace the factor top_counts with all actual frequencies but you could get them separately if needed.

`skim(iris) %>% dplyr::select(-formatted) %>% tidyr::spread(stat, value)`

**Comment by Z3tt** [comment] 2018-01-29 08:52
It is not a lower case w when trying to select Sepal.Width. Anyway, something different going on there...
Thank you very much for figuring that all out. Using skim() is a valid option but I like about skim_to_wide() that I can choose which cols get printed: `skim_to_wide(iris) %>% select(variable, type, n, p0, p100)`. That does not work in combination with skim(). Is there a simple way for that using skim()?

**Comment by elinw** [comment] 2018-01-29 09:28
In the final screenshot you definitely(unless you have a hard to read font) have lower case w which is why it says not found.

If you only want certain statistics you could add a filter to the piping chain above but 
why don't you use skim_with() to select the statistics that you want to display?
Unfortunately there is a bug right now (fixed in develop) so you have to remove the statistics you don't want one at a time: 
```
skim_with(numeric = list(complete=NULL))
skim_with(numeric = list(missing=NULL))
skim_with(numeric = list(mean=NULL))
skim_with(numeric = list(sd = NULL))
skim_with(numeric = list(complete=NULL))
skim_with(numeric = list(missing=NULL))
skim_with(numeric = list(mean=NULL))
skim_with(numeric = list(p25=NULL))
skim_with(numeric = list(median=NULL))
skim_with(numeric = list(p75=NULL))
skim_with(numeric = list(hist=NULL))
iris %>% dplyr::select("Sepal.Length", "Sepal.Width") %>% skim()

skim_with_defaults()
```
We're also looking at the recent changes to the Tibble package to see what impact they have.

**Comment by Z3tt** [comment] 2018-01-29 09:45
It is definitely an upper case W, maybe the screenshot messed it up or it is a hard to read font. There seems to be smt else going on, on my PC at work it is not a problem but at home it just works using skim(iris$Sepal.Width) but not with piping.

Anyway, thought the solution to get rid off double-quoted numbers is to use skim() instead of the other skim_to_wide() and skim_to_list() with their complex print function... Thank you very much for your time and I guess an update will fix all this.

**Comment by elinw** [comment] 2018-01-29 16:57
I think it's really to have a print method specifically for character data because we know there are serious issues with printing character data with data frames which is why we had all the problems with rendering the histograms on Windows.

**Comment by elinw** [comment] 2018-02-16 17:18
I took off the bug label because this is expected behavior when there are spaces at the beginning or end of strings.  The other question, though, is whether we should have the option of returning numeric data in skim_to_*.   The downside of that is that those values will not be the same as the printed values (because the print handles number of decimal places to show) and that might confuse people

**Comment by Z3tt** [comment] 2018-02-21 09:54
Fine for me. I guess you already answered the question. Let it as it is and I learn to deal with it - better than confusing several other people ;)

**Comment by elinw** [comment] 2018-03-06 11:53
I'm going to close this. When we release skimr 2.0 our plan is to have away to return either the numeric or the formatted.

**Closed by elinw** 2018-03-06 11:53 UTC
Labels: Needs discussion
