### ISSUE TITLE
Support `group_by`

### ISSUE THREAD

**Issue by sebastiansauer** [ropenscilabs/skimr#131] opened 2017-09-01 13:16 UTC
Sometimes it is useful to report statistics based on groups, ie., what's the recovery rate in the experimental group compared to the control group. 

In dplyr/tidyverse, building groups is left to `group_by`. However, it appears that this feature is not (yet) supported by `skimr`.

I would expect that this code yields a grouped dataframe, as other tidyverse-code does:
mtcars %>% group_by(cyl) %>% skim

However, the code does not split up the results in groups.

It would be great to have that feature. Many thanks for the great work1 👍

**Comment by elinw** [comment] 2017-09-02 18:54
We actually already have this in the develop branch.  It would be great if you would test it out and give feed back.  There are a couple of discussions of this already in the issue tracker.

**Comment by elinw** [comment] 2017-09-12 18:32
Duplicate of https://github.com/ropenscilabs/skimr/issues/53

**Closed by elinw** 2017-09-12 18:32 UTC
