### ISSUE TITLE
> skim(nino) ; missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by cordphelps** [ropenscilabs/skimr#298] opened 2018-03-02 12:40 UTC
I'm not quite sure how to deal with this error, the docs don't seem to mention skim() options. my dataframe does have some empty cells... is it possibly a bug(?)

you can build the df with

       > library(RCurl)
	> source.url <- c("https://raw.githubusercontent.com/cordphelps/cetacea/master/V81.csv")
	> nino <- read.csv(text=getURLContent(source.url), header=TRUE, row.names=NULL)

or just view the csv directly: https://github.com/cordphelps/cetacea

inspiring work anyway, thank you.

**Comment by michaelquinn32** [comment] 2018-03-02 20:08
Hi Cord!

Thanks for the message.

I'm struggling to reproduce the bug. Can you try it again with the `curl` library?

```
library(curl)
library(skimr)
source.url <- c("https://raw.githubusercontent.com/cordphelps/cetacea/master/V81.csv")
nino <- read.csv(curl(source.url), header = TRUE, row.names = NULL)
skim(nino)
#> Skim summary statistics
#>  n obs: 101 
#>  n variables: 52 
#> 
#> Variable type: integer 
#>                             variable missing complete   n     mean      sd
#>                         ccAnacapaREL       0      101 101  113.12    21.68
#>                          ccBajaCalif       0      101 101 5655.94  1083.89
#>                    ccChannelABSOLUTE       0      101 101  565.59   108.39
#>                       ccSanMiguelREL       0      101 101  113.12    21.68
#>                  ElNinoEventThisYear       0      101 101    0.12     0.33
#>       ElNinoModelMemoryEventLastYear       0      101 101    0.11     0.31
#>                           FINAL.TIME     100        1 101  100       NA   
#>                         INITIAL.TIME     100        1 101    0       NA   
#>                  LaNinaEventThisYear       0      101 101    0.059    0.24
#>       LaNinaModelMemoryEventLastYear       0      101 101    0.059    0.24
#>  LogicalAndElNinoThisYearAndLastYear       0      101 101    0.23     0.42
#>  LogicalAndLaNinaThisYearAndLastYear       0      101 101    0.12     0.33
#>                            popAlaska       0      101 101 5000        0   
#>                              SAVEPER       0      101 101    1        0   
#>                                 Time       0      101 101   50       29.3 
#>                            TIME.STEP     100        1 101    1       NA   
#>    p0  p25 median  p75 p100     hist
#>    50  100    100  125  150 ▁▁▁▇▁▁▁▂
#>  2500 5000   5000 6250 7500 ▁▁▁▇▁▁▁▂
#>   250  500    500  625  750 ▁▁▁▇▁▁▁▂
#>    50  100    100  125  150 ▁▁▁▇▁▁▁▂
#>     0    0      0    0    1 ▇▁▁▁▁▁▁▁
#>     0    0      0    0    1 ▇▁▁▁▁▁▁▁
#>   100  100    100  100  100 ▁▁▁▇▁▁▁▁
#>     0    0      0    0    0 ▁▁▁▇▁▁▁▁
#>     0    0      0    0    1 ▇▁▁▁▁▁▁▁
#>     0    0      0    0    1 ▇▁▁▁▁▁▁▁
#>     0    0      0    0    1 ▇▁▁▁▁▁▁▂
#>     0    0      0    0    1 ▇▁▁▁▁▁▁▁
#>  5000 5000   5000 5000 5000 ▁▁▁▇▁▁▁▁
#>     1    1      1    1    1 ▁▁▁▇▁▁▁▁
#>     0   25     50   75  100 ▇▇▇▇▇▇▇▇
#>     1    1      1    1    1 ▁▁▁▇▁▁▁▁
#> 
#> Variable type: numeric 
#>            variable missing complete   n     mean      sd       p0
#>      ccSantaCruzREL       0      101 101  169.68   32.52    75    
#>      ccSantaRosaREL       0      101 101  169.68   32.52    75    
#>                 con       0      101 101    1.13    0.22     0.5  
#>            disaster       0      101 101    0.005   0.05     0    
#>   ElNinoProbability     100        1 101    0.11   NA        0.11 
#>             flow2.1       0      101 101    5.31    8.99     0    
#>             flow2.3       0      101 101    0.38    0.38     0    
#>             flow2.4       0      101 101    0.31    0.35     0    
#>             flow2.5       0      101 101    0.34    0.36     0    
#>             flow3.1       0      101 101    4.14    9.51     0    
#>             flow3.2       0      101 101    0.38    0.49     0    
#>             flow3.4       0      101 101    0.5     0.57     0    
#>             flow3.5       0      101 101    0.39    0.51     0    
#>             flow4.1       0      101 101    4.77   10.56     0    
#>             flow4.2       0      101 101    0.48    0.54     0    
#>             flow4.3       0      101 101    0.45    0.51     0    
#>             flow4.5       0      101 101    0.43    0.49     0    
#>             flow5.1       0      101 101  243.07  146.92     0    
#>             flow5.2       0      101 101    5.59    3.81     0    
#>             flow5.3       0      101 101    4.69    3.47     0    
#>             flow5.4       0      101 101    5.44    4.34     0    
#>          flowAlaska       0      101 101 4921.35  346.25  2556.9  
#>   flowChannelBypass       0      101 101 4740.82  147.22  4504.21 
#>  flowChannelIslands       0      101 101  259.18  147.22     3.79 
#>          flowHawaii       0      101 101   74.31  259.4      0    
#>   LaNinaProbability     100        1 101    0.083  NA        0.083
#>    migrationBypass.       0      101 101    0.95    0.029    0.9  
#>              mixer2     100        1 101    0.1    NA        0.1  
#>              mixer3     100        1 101    0.1    NA        0.1  
#>              mixer4     100        1 101    0.1    NA        0.1  
#>              mixer5     100        1 101    0.3    NA        0.3  
#>         pop2Anacapa       0      101 101  105.13   13       57.67 
#>       pop3SantaCruz       0      101 101  150.53   16.8     80.07 
#>       pop4SantaRosa       0      101 101  153      16.95    73.69 
#>       pop5SanMiguel       0      101 101  356.13  148.45    94.12 
#>        popBajaCalif       0      101 101 4921.35  346.25  2556.9  
#>       p25   median      p75     p100     hist
#>   150      150      187.5    225     ▁▁▁▇▁▁▁▂
#>   150      150      187.5    225     ▁▁▁▇▁▁▁▂
#>     1        1        1.25     1.5   ▁▁▁▇▁▁▁▂
#>     0        0        0        0.5   ▇▁▁▁▁▁▁▁
#>     0.11     0.11     0.11     0.11  ▁▁▁▇▁▁▁▁
#>     0        2.34     6.48    59.08  ▇▁▁▁▁▁▁▁
#>     0        0.36     0.69     1.17  ▇▁▁▂▂▂▂▁
#>     0        0.22     0.62     1.25  ▇▂▂▁▁▂▁▁
#>     0        0.19     0.64     1.07  ▇▂▂▁▂▂▁▂
#>     0        0.39     5.2     81.23  ▇▁▁▁▁▁▁▁
#>     0        0.046    0.7      1.54  ▇▁▁▁▁▁▁▁
#>     0        0.28     1.05     1.64  ▇▁▁▁▂▂▁▂
#>     0        0.024    0.74     1.52  ▇▁▁▁▁▁▁▁
#>     0        0.69     6.36    88.64  ▇▁▁▁▁▁▁▁
#>     0        0.31     0.88     1.6   ▇▁▂▂▁▁▁▂
#>     0        0.24     0.86     1.58  ▇▁▁▁▂▁▂▁
#>     0        0.16     0.95     1.48  ▇▁▁▁▁▂▁▁
#>   115.64   236.53   388.82   492.47  ▇▇▇▇▆▃▇▇
#>     2.8      5.05     7.41    16.67  ▆▇▇▆▂▂▁▁
#>     1.3      4.19     7.13    14.58  ▇▃▅▃▃▂▁▁
#>     1.68     4        8.51    16.38  ▇▆▃▂▃▃▁▁
#>  4756.31  4970.93  5146.5   5402.08  ▁▁▁▁▁▃▇▆
#>  4591.16  4752.63  4860.3   4996.21  ▇▃▂▅▅▇▅▃
#>   139.7    247.37   408.84   495.79  ▃▅▇▅▅▂▃▇
#>     0        0       39.57  2468.08  ▇▁▁▁▁▁▁▁
#>     0.083    0.083    0.083    0.083 ▁▁▁▇▁▁▁▁
#>     0.92     0.95     0.97     1     ▇▃▂▅▅▇▅▃
#>     0.1      0.1      0.1      0.1   ▁▁▁▇▁▁▁▁
#>     0.1      0.1      0.1      0.1   ▁▁▁▇▁▁▁▁
#>     0.1      0.1      0.1      0.1   ▁▁▁▇▁▁▁▁
#>     0.3      0.3      0.3      0.3   ▁▁▁▇▁▁▁▁
#>   102.22   105.78   110.04   135.59  ▁▁▁▁▇▆▂▁
#>   150      153.4    157.99   178.72  ▁▁▁▁▁▇▇▁
#>   150.69   154.57   159.83   185.5   ▁▁▁▁▁▇▅▁
#>   239.62   345.03   496.88   625.5   ▅▅▇▅▇▃▇▅
#>  4756.31  4970.93  5146.5   5402.08  ▁▁▁▁▁▃▇▆
```

**Comment by elinw** [comment] 2018-03-03 02:39
Or replace `text=getURLContent(source.url)` with `source.url`.

**Comment by cordphelps** [comment] 2018-03-03 07:31
> source.url <- c("https://raw.githubusercontent.com/cordphelps/cetacea/master/V81.csv")
> nino <- read.csv(text=getURLContent(source.url), header=TRUE, row.names=NULL)
> skim(nino)
Error in if (all(x == 0)) x <- x + 1 : 
  missing value where TRUE/FALSE needed
> summary(nino)     # this works
> View(nino)            # this works

ggplot happily manipulates nino....

I am on OSX 10.11.6

R says: R 3.3.3 GUI 1.69 Mavericks build (7328)

I actually encountered this originally when I read the csv off my local disc, I now duplicte
(above) reading it from github (so I don't think my read.csv() is contributing).

I just grabbed library skimr yesterday from CRAN, and I don't know how to check the rev ; if you want it, please tell me how. 

Thank you for your effort.

**Comment by cordphelps** [comment] 2018-03-03 07:37
sorry I missed @michaelquinn32 's request:

> library(curl)
> library(skimr)
> source.url <- c("https://raw.githubusercontent.com/cordphelps/cetacea/master/V81.csv")
> nino <- read.csv(curl(source.url), header = TRUE, row.names = NULL)
> skim(nino)
Error in if (all(x == 0)) x <- x + 1 : 
  missing value where TRUE/FALSE needed
> 

( no help! )

**Comment by elinw** [comment] 2018-03-03 12:57
Okay so can you please check your dataset before skimming and make sure if it is okay? 

Please try adding this before skimming:

`skim_with(numeric=list(hist=NULL))`

Also what operating system are you on?

**Comment by elinw** [comment] 2018-03-03 13:17
So the line you are showing does not have `na.rm = TRUE` and that's why it is failing.  This already came up and it is fixed in master, but not released.  If you are willing to install from github you can have it fixed. 
@michaelquinn32 I'm thinking we should do a new bug fix release since we've fixed a number of things and the next changes are likely to be more high impact.

**Comment by elinw** [comment] 2018-03-04 02:55
I'm going to close this since I have pushed the fix into master.  If you do a github install from master it should work for you.

**Closed by elinw** 2018-03-04 02:55 UTC
