### ISSUE TITLE
weird output formatting 

### ISSUE THREAD

**Issue by mtjhrsk** [ropenscilabs/skimr#54] opened 2017-05-27 16:43 UTC
Hi there,
trying to work with the package, I am getting this result:

![image](https://cloud.githubusercontent.com/assets/3810592/26522958/0ae0a64a-430c-11e7-99f2-270598dbb4c2.png)

I guess there is an easy and straightforward solution, but nothing works so far (changing encoding, reinstalling packages). Maybe you have seen something similar.
Thanks!

**Comment by haozhu233** [comment] 2017-05-27 17:44
The <u+***> things you saw is supposed to be the histogram. My current guess is the computer encoding issue? Maybe you can try to install hadley/colformat again?

**Comment by mtjhrsk** [comment] 2017-05-27 17:52
thanks for your suggestions, already tried reinstalling both packages and changing encoding, still getting the same result. which encoding works for you?

**Comment by cedricbatailler** [comment] 2017-05-28 18:37
I got the same problem if I can help for troubleshooting.

**Comment by mtjhrsk** [comment] 2017-05-29 10:01
just tried the examples on linux (x86_64-pc-linux-gnu, Ubuntu 17.04) and it works without an issue (R version 3.4.0 (2017-04-21). still having formatting problems on windows, even after updating to R 3.4.0 from 3.3.3.

**Comment by haozhu233** [comment] 2017-05-29 20:31
Yeah, I also tested on my windows machine and I can see the raw unicode. Hadley's colformat does work on Windows (at least in the console) so my current guess is that when it was put into the table and being spread, it was converted to plain text string in Windows. It's certainly a bug that needs to be fixed. Thanks everyone for reporting.

**Comment by dsdesrosiers** [comment] 2017-06-01 19:25
Same thing for me...here's my session info which I notice is slightly different than that shown for the linked issue #64 

R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] colformat_0.0.0.9000 skimr_1.0            dplyr_0.5.0          purrr_0.2.2.2        readr_1.1.1          tidyr_0.6.3         
 [7] tibble_1.3.3         ggplot2_2.2.1        tidyverse_1.1.1      devtools_1.13.1     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10          cellranger_1.1.0      compiler_3.4.0        git2r_0.18.0          plyr_1.8.4            forcats_0.2.0        
 [7] tools_3.4.0           digest_0.6.12         lubridate_1.6.0       jsonlite_1.4          memoise_1.1.0         nlme_3.1-131         
[13] gtable_0.2.0          lattice_0.20-35       rlang_0.1.1           psych_1.7.5           DBI_0.6-1             rstudioapi_0.6.0.9000
[19] curl_2.6              parallel_3.4.0        haven_1.0.0           xml2_1.1.1            withr_1.0.2           httr_1.2.1           
[25] stringr_1.2.0         hms_0.3               grid_3.4.0            R6_2.2.1              readxl_1.0.0          foreign_0.8-67       
[31] modelr_0.1.0          reshape2_1.4.2        magrittr_1.5          scales_0.4.1          rvest_0.3.2           assertthat_0.2.0     
[37] mnormt_1.5-5          colorspace_1.3-2      stringi_1.1.5         munsell_0.4.3         lazyeval_0.2.0        broom_0.4.2          
[43] crayon_1.3.2.9000

**Comment by AndrewKostandy** [comment] 2017-06-02 22:33
I'm facing the same issue on Mac OS. Instead of the histogram for a variable, I'm getting: "\u2582\u2587\u2582\u2587\u2587\u2583\u2587\u2586\u2582\u2582"

R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] colformat_0.0.0.9000 dplyr_0.5.0          skimr_1.0            devtools_1.13.2     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11        tidyr_0.6.3         withr_1.0.2         digest_0.6.12      
 [5] crayon_1.3.2.9000   assertthat_0.2.0    R6_2.2.1            DBI_0.6-1          
 [9] git2r_0.18.0        magrittr_1.5        httr_1.2.1          rlang_0.1.1        
[13] curl_2.6            lazyeval_0.2.0.9000 rstudioapi_0.6      tools_3.4.0        
[17] purrr_0.2.2.2       compiler_3.4.0      memoise_1.1.0       tibble_1.3.3

**Comment by elinw** [comment] 2017-06-03 01:39
Are you using devtools::install_github() or installing from CRAN? You need to have the development version.

**Comment by AndrewKostandy** [comment] 2017-06-03 01:42
I've installed both colformat & skimr with devtools::install_github().

**Comment by elinw** [comment] 2017-06-04 16:11
Seems like bugzilla contains some reports about unicode and Windows but I'm okay on a mac.

R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testthat_1.0.2 skimr_1.0     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11         tidyr_0.6.3.9000     crayon_1.3.2.9000    dplyr_0.5.0          assertthat_0.2.0    
 [6] R6_2.2.1             DBI_0.6-1            magrittr_1.5         stringi_1.1.5        rlang_0.1.1         
[11] lazyeval_0.2.0       rstudioapi_0.6       tools_3.4.0          stringr_1.2.0.9000   purrr_0.2.2.9000    
[16] compiler_3.4.0       colformat_0.0.0.9000 tibble_1.3.3

**Comment by elinw** [comment] 2017-06-04 16:14
Can you try changing locale to support UTF-8?

**Comment by AndrewKostandy** [comment] 2017-06-04 23:55
Alright, that worked! Thanks elinw.

On RStudio I entered:

`Sys.setlocale("LC_ALL", 'en_US.UTF-8')`

At that point it started working.

When I checked my locale in the Mac OS Terminal I got:
![screen shot 2017-06-05 at 3 41 50 am](https://cloud.githubusercontent.com/assets/13706356/26766404/37c356a2-49a2-11e7-8c06-50c245ef3a58.png)

I then entered the following on the Terminal to set LC_ALL to the UTF-8 on the system as well.
`export LC_ALL=en_US.UTF-8 `

**Comment by grepinsight** [comment] 2017-06-05 02:42
On windows, I get the following message

```
> Sys.setlocale("LC_ALL", 'en_US.UTF-8')
[1] ""
Warning message:
In Sys.setlocale("LC_ALL", "en_US.UTF-8") :
  OS reports request to set locale to "en_US.UTF-8" cannot be honored
```

**Comment by elinw** [comment] 2017-06-05 10:50
http://people.fas.harvard.edu/~izahn/posts/reading-data-with-non-native-encoding-in-r/  explains  the issue.  Maybe readr can help here.

**Comment by cedricbatailler** [comment] 2017-06-05 11:17
```
library(tidyverse)

skimr::skim(mtcars) %>% 
  filter(stat == "hist") %>% 
  print.listof(locale = locale(encoding = "UTF8"))
```

Code above gets histogram to get printed correctly on Windows so I guess you figured out what the problem is!

**Comment by mtjhrsk** [comment] 2017-06-05 11:27
thanks @cedricbatailler @elinw, output is a bit messy, but works on my windows machine as well.

**Comment by elinw** [comment] 2017-06-07 02:16
Great! I'm going to close this issue but we should document this.

**Closed by elinw** 2017-06-07 02:16 UTC
Labels: bug
