### ISSUE TITLE
requires to_character()?

### ISSUE THREAD

**Issue by emilynz** [ropenscilabs/skimr#297] opened 2018-02-28 04:20 UTC
When trying to run `kable()` (because I'm on windows at work and `pander()` told me to), I get the message:
`Error in to_character(as.matrix(x)) : 
  could not find function "to_character"`
This is resolved by installing and loading the `labelled` package. 

I feel like there should be a way to get around this in the package, rather than me having to load this externally, but I'm still so vague about how packages work so I'm not really sure. Hopefully it's an easy fix...?

Fully reproducible (I hope) example:
```
library(skimr)
library(tidyverse)
skim(iris) %>% kable()
```

**Comment by elinw** [comment] 2018-02-28 19:30
You need to make sure you are using our version of kable ... can you try namespacing the function call to skimr::kable() and letting me know if that solves it?

**Comment by emilynz** [comment] 2018-02-28 21:30
I can confirm that `skimr::kable()` produces the same error. 

I may not have all the most up to date versions of tidyverse packages, maybe updating all of those would help? But I do have the newer ones than listed in the documentation (`Imports: dplyr (>= 0.7), magrittr, pander, purrr, rlang, stats, stringr (>= 1.1), knitr, tibble (>= 0.6), tidyr (>= 0.7), tidyselect` ).

**Comment by elinw** [comment] 2018-03-01 00:39
Can you try loading skimr after tidyverse?
I'm looking in the repos for the different tidyverse packages and I'm not finding a place where they call the labelled package.
Are you using that package?

**Comment by emilynz** [comment] 2018-03-01 01:14
Without tidyverse it gives the same error. I just left it in the example because I tend to load it first at the top of most scripts.

When I googled `to_character()` the `labelled` package was the only thing that came up, and when I installed and loaded it the `kable()` command worked...

**Comment by elinw** [comment] 2018-03-01 12:53
So the issue is that our `kable()` function does not refer to to_character nor is it referenced in `knitr::kable()`.   So then the question is why is it called? There is no reason at all why anything in the iris data set would have to be changed to a character.  We use `is.character()` in skim_v.R but that's not what you are seeing.    Would it be possible for you to try starting a new session and skimming iris, then skimming to kable?

**Comment by emilynz** [comment] 2018-03-01 22:29
Might it be something to do with being on a Windows machine? Or using Rstudio? I've started a new session and run:
```
summary <- skimr::skim(iris)
skimr::kable(summary)
```
And the output is still:
```
Skim summary statistics  
 n obs: 150    
 n variables: 5    

Variable type: factorError in to_character(as.matrix(x)) : 
  could not find function "to_character"
```

Is there a way of tracing back this error to work out where it is trying to call `to_character()` from?

**Comment by elinw** [comment] 2018-03-02 02:00
Okay so  the mystery is where to_character is, because it is not in skimr. 
`to_character(as.matrix(x))`  is not in our code.
https://github.com/ropenscilabs/skimr/blob/master/R/kable.R
Shows the kable function. The difference is for windows uses `fix_unicode()`.
https://github.com/ropenscilabs/skimr/blob/master/R/utils.R
Doesn't use as_character and doesn't call labelled.   
If you would turn on debugging and see if you can get a decent back trace to figure out where that call to as_character is coming from it would be good.
https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio
I'll see if I can find a windows machine.

**Comment by elinw** [comment] 2018-03-02 02:03
Are you doing this in the console or when knitting?

**Comment by joesanderson** [comment] 2018-03-02 15:14
When looking at the skimr::kable.data.frame code in the code viewer in Rstudio, there is `x = replace_na(to_character(as.matrix(x)), is.na(x))` on line 83.

As this isn't in your codebase, I assume it's come from the knitr codebase, where they do have an unexported `to_character()' function - if I load the knitr package manually the error goes away.

**Comment by joesanderson** [comment] 2018-03-02 15:18
Actually, scratch that - I still get a `could not find function "to_character"` error when trying to directly call `skimr::kable` on a `skim` call - the error only goes away when knitr masks the skimr version of kable()

**Comment by elinw** [comment] 2018-03-03 02:47
Is this in the console? I don't see why it would be platform related but are you on Windows?

**Comment by joesanderson** [comment] 2018-03-03 08:17
I get it both in the console and when knitting, and I am on Windows

**Comment by elinw** [comment] 2018-03-03 13:23
So one puzzle is why it is calling kable.data.frame when it should be doing kable.skim_df. 
Would you please do the following and report back exactly what you get?
`class(skim(iris))` 

Also I assume you are using the CRAN version of skimr, is that right?

**Comment by joesanderson** [comment] 2018-03-03 23:23
The class of the skim output object is: `"skim_df"    "tbl_df"     "tbl"        "data.frame"`, and yes, I'm using the CRAN version. My session info (I'm doing this is a new R session) is:

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
> [3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
> [5] LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] tools_3.3.2

**Comment by elinw** [comment] 2018-03-05 15:05
Okay so the issue you both are seeing could be due to Windows I guess, but it seems strange that would be the case especially since we run a lot of tests on iris and they pass on windows.  It could also potentially be something with the collation/locale in which English_United Kingdom is somehow different that English_United States. @emilynz  can you check your environment to see what your collation and locale are?
I'm suspicious that there is an issue somehow related to the order of loading knitr and skimr, but it seems not obvious what that is in the testing I have done so far.
If you would let me know about whether knitting is behaving differently than the console that would be helpful.
Also can you try some other sample data such as `mtcars`, `lynx` and`CO2`?
Thanks!

**Comment by emilynz** [comment] 2018-03-05 21:57
Hiya, my sessionInfo is:

> R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
>
> locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
[3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
[5] LC_TIME=English_New Zealand.1252     
>
> attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
>
> loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    yaml_2.1.14 


results from other sample data in the console:
```
> skimr::kable(skimr::skim(mtcars))
Skim summary statistics  
 n obs: 32    
 n variables: 11    

Variable type: numericError in to_character(as.matrix(x)) : 
  could not find function "to_character"

> skimr::kable(skimr::skim(lynx))
Error in to_character(as.matrix(x)) : 
  could not find function "to_character"

> skimr::kable(skimr::skim(CO2))
Skim summary statistics  
 n obs: 84    
 n variables: 5    

Variable type: factorError in to_character(as.matrix(x)) : 
  could not find function "to_character"
```
Same issue (error) with knitting.

**Comment by joesanderson** [comment] 2018-03-05 23:16
My output from those built-in datasets is identical:
```
> skimr::kable(skimr::skim(mtcars))
Skim summary statistics  
 n obs: 32    
 n variables: 11    

Variable type: numeric
Error in replace_na(to_character(as.matrix(x)), is.na(x)) : 
  could not find function "to_character"
> skimr::kable(skimr::skim(lynx))
Error in replace_na(to_character(as.matrix(x)), is.na(x)) : 
  could not find function "to_character"
> skimr::kable(skimr::skim(CO2))
Skim summary statistics  
 n obs: 84    
 n variables: 5    

Variable type: factor
Error in replace_na(to_character(as.matrix(x)), is.na(x)) : 
  could not find function "to_character"
```
I've tried changing my locale to English_United States, but that doesn't seem to help:

```
> Sys.setlocale(locale = "english")
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     tidyr_0.8.0      digest_0.6.9     dplyr_0.7.4      assertthat_0.1  
 [6] R6_2.1.2         magrittr_1.5     stringi_1.0-1    rlang_0.2.0      skimr_1.0.1     
[11] tools_3.3.2      stringr_1.2.0    pander_0.6.0     glue_1.2.0       purrr_0.2.2     
[16] pkgconfig_2.0.1  knitr_1.15       bindr_0.1        tidyselect_0.2.4 tibble_1.3.4    
> skimr::kable(skimr::skim(mtcars))
Skim summary statistics  
 n obs: 32    
 n variables: 11    

Variable type: numeric
Error in replace_na(to_character(as.matrix(x)), is.na(x)) : 
  could not find function "to_character"
```

**Comment by elinw** [comment] 2018-03-07 16:14
So the only thing I see in common is

> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)

Since you have different versions of R, different locales, but the Appveyor runs on

> R version 3.4.3 Patched (2018-03-02 r74345)
> Platform: i386-w64-mingw32/i386 (32-bit)
> Running under: Windows Server 2012 R2 x64 (build 9600)

@michaelquinn32 do you know if it is possible to run the tests on 64-bit?   I'm also wondering if the Windows Server versus Windows >=8 could make a difference.

**Comment by elinw** [comment] 2018-03-08 14:06
Here is the function:

```

to_character = function(x) {
  if (is.character(x)) return(x)
  x2 = as.character(x); dim(x2) = dim(x); dimnames(x2) = dimnames(x)
  x2
}
```

If you execute that and then do skimr::kable(skim(iris))  does it work?   (or other data).
I wonder if Yihue would be okay with us copying it, if it does solve the problem.

**Comment by elinw** [comment] 2018-03-08 16:21
Also would you try updating your knitr? @emilynz @joesanderson

**Comment by joesanderson** [comment] 2018-03-08 18:01
Yes, loading the `to_character` function into the global env does allow it to work, but updating my knitr version to 1.20 doesn't help

**Comment by emilynz** [comment] 2018-03-08 22:56
I have updated knitr to version 1.20 and it now works for me!

**Comment by elinw** [comment] 2018-03-09 03:30
Okay that's contradictory! My local test and @emilynz  found that updating fixed but @joesanderson's results indicate that it didn't help.   

Also I realized another strange thing which is that Emily tried using the function from the labelled package which does something completely different but also worked.  Since we are only printing characters I guess it's not surprising.

**Comment by elinw** [comment] 2018-03-09 14:57
@joesanderson 
What if you use this

`to_character = function() {}`

**Comment by joesanderson** [comment] 2018-03-09 22:46
Wow - it works with that empty function! 

I get the following warning:
```
Warning message:
In opts_knit$get("rmarkdown.pandoc.to") :
  bytecode version mismatch; using eval
```
with `mtcars`, but no errors or warnings with `lynx` or `CO2`

**Comment by elinw** [comment] 2018-03-10 20:03
Yeah the function is not doing anything at all because the data are already characters.   But that is definitely an interesting message!

**Comment by elinw** [comment] 2018-03-12 14:21
It seems like usually that message is generated when something with the versioning is out of sync. For example you have a package that was built on a different version of R.  I also looked around for information about the context, and it is in a combination of rmarkdown and knitr, so I wonder if updating rmarkdown might help.  This gave me some information (though not a solution) https://stackoverflow.com/questions/35144130/in-knitr-how-can-i-test-for-if-the-output-will-be-pdf-or-word.

**Comment by elinw** [comment] 2018-03-14 12:32
I think that updating `knitr` to the newest version which is build on R 3.4.x probably triggered the pandoc issue.

**Comment by elinw** [comment] 2018-03-28 11:32
I'm closing this, marking it resolved based on the minimum version of knitr.  I've also added, for now, advice to users that says that if they see this problem they can create an empty to_character() function. Whatever is continuing to cause the problem for @joesanderson  is a separate issue that I don't know if we can figure out until we get a second person reporting unless Joe wants to dig into it on his machine. I think the pandoc issue is related but again it may require us to have a second reporter and it probably relates to the version of one or more pakages. I'm going to close this issue but we can open a different issue if that makes sense or just wait and see.

**Closed by elinw** 2018-03-28 11:33 UTC
Labels: Fixed in Develop, bug, outputs
